---- LOOK AND FEEL ----
-----------------------

-- Refer to https://wiki.hypr.land/Configuring/Basics/Variables/

-- Border colors - dynamically generated by wallust from your current
-- wallpaper (see config/wallust/wallust.toml). Falls back to
-- config/hypr/colors.lua's checked-in defaults until wallust has run
-- at least once.
local colors = require("colors")

hl.config({
	general = {
		gaps_in = 5,
		gaps_out = 5,

		border_size = 1,

		col = {
			active_border = { colors = { colors.active_border, colors.active_border }, angle = 45 },
			inactive_border = colors.inactive_border,
		},

		-- Set to true to enable resizing windows by clicking and dragging on borders and gaps
		resize_on_border = false,

		-- Please see https://wiki.hypr.land/Configuring/Advanced-and-Cool/Tearing/ before you turn this on
		allow_tearing = false,

		layout = "dwindle",
	},

	decoration = {
		rounding = 5,
		rounding_power = 2,

		-- Change transparency of focused and unfocused windows
		active_opacity = 1.0,
		inactive_opacity = 0.8,

		shadow = {
			enabled = true,
			range = 4,
			render_power = 3,
			color = 0xee1a1a1a,
		},

		blur = {
			enabled = true,
			size = 3,
			passes = 1,
			vibrancy = 0.1696,
		},
	},

	animations = {
		enabled = true,
	},
})
