#!/usr/bin/env bash

########################################
# Fix SDDM greeter's own Hyprland config
########################################
#
# SDDM's greeter runs its own separate,
# minimal Hyprland session (as the system
# "sddm" user, via CompositorCommand in
# /etc/sddm.conf) just to render the login
# screen - this is a completely different
# session from your own, with its own
# config path, and HyprX's install/deploy
# has never touched it.
#
# With no config file there, Hyprland
# auto-generates one on the fly - which is
# exactly what causes the "Warning: You're
# using an autogenerated config!" banner,
# the default Hyprland wallpaper flash, and
# the built-in keybind cheatsheet on the
# SDDM login screen. None of that is
# controlled by your own hyprland.lua.
#
# This writes a minimal, valid config at
# that path so Hyprland has something real
# to load instead of generating a default -
# just enough to suppress the logo/
# wallpaper flash and the warning banner.
# Nothing else about the greeter changes.
#
# Requires sudo (the file must be owned by
# the "sddm" user, not you). Run manually,
# once:
#     sudo bash scripts/fix-sddm-greeter.sh
#

set -euo pipefail

GREETER_CONFIG_DIR="/var/lib/sddm/.config/hypr"
GREETER_CONFIG_FILE="$GREETER_CONFIG_DIR/hyprland.lua"

if [[ "$(id -u)" -ne 0 ]]; then
    echo "This needs to run as root (writes to $GREETER_CONFIG_DIR, owned by the sddm user)." >&2
    echo "Run: sudo bash scripts/fix-sddm-greeter.sh" >&2
    exit 1
fi

if [[ -f "$GREETER_CONFIG_FILE" ]]; then
    backup="$GREETER_CONFIG_FILE.bak.$(date +%Y%m%d%H%M%S)"
    cp "$GREETER_CONFIG_FILE" "$backup"
    echo "Backed up existing config to $backup"
    # No "skip if exists" guard: this file is only ever either
    # missing, or the one Hyprland itself auto-generates the first
    # time the greeter runs with no config (that's exactly what the
    # "autogenerated config" warning banner on the login screen
    # means) - nobody hand-customizes SDDM's own separate greeter
    # session, so there's nothing here worth preserving. Back it up
    # anyway, on principle, then always write the real fix.
fi

mkdir -p "$GREETER_CONFIG_DIR"

cat > "$GREETER_CONFIG_FILE" << 'EOF'
-- Minimal config for SDDM's own greeter Hyprland session.
-- This is NOT your session's config (that's ~/.config/hypr/hyprland.lua) -
-- this only exists to stop the greeter from auto-generating a default
-- config (which shows a warning banner, keybind cheatsheet, and the
-- default Hyprland wallpaper on the login screen).

hl.config({
	misc = {
		force_default_wallpaper = 0,
		disable_hyprland_logo = true,
	},
})
EOF

chown -R sddm:sddm "$GREETER_CONFIG_DIR" 2>/dev/null || \
    echo "Note: could not chown to sddm:sddm (continuing - file is still readable)."

echo "Wrote $GREETER_CONFIG_FILE"
echo "Reboot (or restart sddm.service) to see the login screen without the flash/banner."
