name: HyprX CI

on:
  push:
    branches:
      - master
      - dev

  pull_request:

  workflow_dispatch:

jobs:

  lint:

    name: Lint

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Install ShellCheck

        run: |
          sudo apt update
          sudo apt install -y shellcheck

      - name: Bash Syntax

        run: bash tests/test_syntax.sh

      - name: ShellCheck

        run: bash tests/test_shellcheck.sh

  tests:

    name: Unit Tests

    runs-on: ubuntu-latest

    needs: lint

    steps:

      - uses: actions/checkout@v4

      - name: Run Tests

        run: bash tests/run.sh